---
title: Genetika
date: 31.5.2021
output: pdf_document
---

# Genetika
- veda o dedičnosti a premenlivosti živočíchov

## Človek
- **23 párov chromozómov**
- 1. až 22. pár -> autozómy(somatické/telové)
- 23. pár -> **pohlavný, gonozómy** (pohlavné)
    - XY
    - XX
- dvojica chromozómov -> **homologický pár**
    - rovnaká veľkosť, rovnaký tvar, nesú **rovnakú** informáciu pre rovnakú vlastnosť (na rovnakom mieste)
    - pri eukariotických bunkách -> **gén => 2 alely**
	- alela **dominantná**
	- alela *recesívna*
	- **DD**: tmavooký, **D***R*: tmavooký, *RR*: bledooký
	- dominantná: veľké písmeno(A), recesívna: malé písmeno(a)
	    - rovnaká vlastnosť, rovnaké písmeno
	- **AA** -> homozygot dominantný
	- *aa* -> homozygot recesívny
	- **A***a* -> heterozygot
	- miesto na ktorom je umiestnená alela sa volá **Lopus**
- *vlastnosť* == **znak**
- **genotyp** -> súbor všetkých génov v organizme
- **fenotyp** -> vonkajší prejav génov 
- **trojica dusíkatých báz** sa volá **triplet** 
    - **triplet** kóduje jednu **aminokyselinu**
- **kodón** -> triplety v DNA a mRNA 
- **antikodón** -> triplet v tRNA

## Expresia génu
- prevod genetickej informácie do poradia aminokyselín v bielkovine
- 2 fázy
    - 1 transkripcia -> prepis gen. informácie z DNA do mRNA
    - 2 translácia -> preklad kodónov z mRNA do poradia aminokyselín
- DNA polymeráza -> rozpletie DNA na 2 reťazce
- vytvorí sa vlákno mRNA
- mRNA -> opustí jadro bunky cez jadrové póry, prejde cez citoplazmu a pripojí sa na ribozóm
- mRNA sa presúva po ribozóme a prečíta sa kodón 
- na priraďovacom mieste sa napojí cez tRNA aminokyselina 
- na odsúvacom mieste sa tRNA odsunie bez aminokyseliny
- **nezmyselné kodóny** -> medzi kodónmi, označujú začiatok a koniec genetického reťazca

---
# TODO: pozri si na utube transkripciu a translaciu
---

## RNA
- mRNA -> mediátorová RNA (messangerová/ informačná)
- tRNA -> transferová RNA
- rRNA -> ribozómová RNA


# Mendelove zákony
- zákony kríženia (hybridizácia)

## Zákon o uniformite prvej generácie
- **zápis: X(zápis kríženia)**
- P: -> rodičovská generácia(parentálna)
- G: -> gamety 
- $F_1$: prvá filiálna generácia
- krížia sa len homozygoty
- **AA x AA, aa x aa, AA x aa**
- ?všetci jedinci uniformný?

## Zákon o segregácii alel a ich voľnej kombinácii

## Zákon o dihybridizácii plody. zelené a žlté

# Stuff

---
# hmmm
---

- dedičnosť
    - s úplnou dominanciou
    - s úplnou recesiou
- intermediarita
    - vo fenotype sa prejavia obe

## Delenie chromozómov
- autozómy - nepohlavné
- gonozómy - pohlavné 
- posledné dva (pár) sú pohlavné

### Chromozómové určenie pohlavia
- cicavčí typ (typ drosofila(mucha))
    - samica = XX, samec = XY 
- vtáčí typ (typ motýlí, typ abraxas)
    - samica = XY, samec = XX
- zápis dedičnosti
    - P: $X_H$ $X_h$ x $X_H$ Y
    - G: $X_H$; $X_h$ $X_H$; Y
- syndrómy 
    - zmeny v počte chromozómov
    - Downow, triomáza 21. p
- enzymopatie
    - poruchy génu v ktorom sú zapísané nzýmy

## Enzymopatie
- Alkaptonúra
    - 1: 19000
- Gelaktozémia
    - 1: 10000
    - v mlieku je galaktóza
- Albinizmus
    - albín, chýba kožný pigment

## Syndrómy
- Downow syndróm - Triómia 21
    - na Slovensku - 1: 700
    - vekom matky predpoklad narastá
- Patavov syndróm - Trizomia 13
    - vážne poškodenie nervovej sústavy
    - často to poskytuje hlavne dievčatá
    - ráštepy podnebia
- Edwardsov syndróm - Trizómia 18
    - vážne poškodenia srdca
    - 1: 7500
- Turnerov syndróm - Monozoómia X
    - 1: 4000
    - postihuje dievčatá
    - prejav -> nízke, neplodné, nevyvinuté pohlavné orgány
- Klimefelterov s. - trizómia XXY
    - to iste čo turnerov s. ale u chlapcov
- supermuž - trizómia XYY
    - znížené IQ a výrazne zvýšené pohlavné znaky
    - agresivita
    - 1: 1000
- superžena - trizómia XXX
    - to isté čo predtým ale u žien
