---
title: A letter to a friend
author: Kapko
output: pdf_document
---

Hi Mark,

I've been wanting to **get back to** you for quite some time now, but I never really had the time for it. But thankfully, now I have a few minutes to spare, so here I go rambling about what I've been up to these past few months.

Sadly we didn't get to go on a **vocation** this year because of the virus. I've been home since March and I'd hoped the situation would get better during the summer, but sadly it didn't so I had to **get over** it and just **get on with** my life. Well there were times, during the summer, when I went away for a bit, actually. I'm sure you remember that we bought an old house from my uncle and that we were finally **getting around to** rebuilding it. So we went to the house with my dad and my grand dad and I helped them dismantle the old house. We were mostly separating wood from other parts and also removing some nails that were left in the wood, a task which almost **became second nature** to both me and my grand dad. At first, we **did things by the book**, but we later realised that, that is too tiresome and time consuming so we just began **cutting corners**.

It's kind of depressing, thinking, that this was the most exciting part of my summer. We later got to go to school for a whole month during September, but due to many new virus cases, we were promptly sent back home. And it's been the same ever since. I really found myself feeling the **fatigue** set in. I mean, don't get me wrong, it's always nice to have more **flexibility**, **regardless** of your situation, but I've began to feel less **motivated** these past few months. I know it sounds weird, but I'm actually looking forward to going back to school again.

So this has been my life the past couple of months. I sincerely hope you and your family are staying safe and I'm looking forward to hearing from you again soon!

Best wishes,

Johnny from Slovakia
