---
title: Prva svetova vojna
author: Septima
output: pdf_document
---

# Medzinarodna situacia pred 1.svetovou vojnou
- vojnový konflikt sa vmedzinárodnom meradle pripravoval už od 70. rokov 19. stor.
- príčiny teda spočívajú vmnožstve protichodných záujmov a napatí medzi vyspelými krajinami sveta, kt.vyplývali z :
  - hospodárskej rivality 
  - boja o zdroje nerastných surovín
  - odbytiská nových tovarov
  - úsilia o koloniálne vlastníctvo-toto súperenie viedlo kboju o rozdelenie sveta = imperializmus,vznikol vo VB v 70. rokoch 19. stor
- okrem tradičných veľmocí (Fr., VB, Rusko) zasiahol imperializmus aj nové mocnosti (Japonsko, USA,Nemecko, Tal., Belgicko)

## VB
- najsilnejšia koloniálna veľmoc
- cieľ:
  - expanzívna imperiálna politika
  - získať oblasti popri námornej ceste do Indie
- ovládla:
  - východ. a juž. Afriku
  - Australiu
  - Kanadu
  - Indiu

## Francuzsko
- francúzsky imperializmus sa sústredil na 2 oblasti:
  1. na tzv. Čiernu Afriku (záp. a stred. Afrika)
  2. na fran. Indočínu (Laos, Vietnam)
  - 1898 Fašodská kríza (Francúzi uznali britské panstvo nad celým údolím Nílu)
- koloniálnej vojne sa predišlo dohodou medzi oboma štátmi a došlo krozdeleniu záujmovej sféry vplyvuv Afrike

## Nemecko
- po štátnom zjednotení vr. 1871 sa vytvorili podmeinky pre mohutný rozvoj hospodárstva (hlavnepriemyslu)
- stali sa 2. najvyspelejším štátom po USA
- Nemecko otovorene hovorilo o „vydobytí si miesta pod slnkom“
- usilovali sa získať nové územia
- situáciu snevoľou sledovala VB a Fran., kt. sa obávali o svoje koloniálne panstvá

## Rusko
- usilovalo sa získať vačší vplyv na Balkáne, Blízkom Východe a ovládnuť Čiernomorké úžiny a RakuskoUhorsko
- najslabšia európská veľmoc, kt. sa usilovala o expanziu na Balkán

# Spojenectva
- Každá ztýchto veľmocí sa obávala izolácie, preto sa usilovala nájsť si spojenca na presadeneie svojichcieľov.
- 1879 (7. 10.) nemecký vyslanec Reuss a rakúsky minister Andráši podpísali vo Viedni tajnú zmluvu orakúsko-nemeckom spojenectve => Dvojspolok
- 1882 (30. 5.) k Dvojspolku sa pridružilo Taliansko => Trojspolok
- 1883 sa voľne pridružilo Rumunsko
- 1892 (17. 9.) uzavretie rusko-francúzskej vojenskej dohody o vzájomnej pomoci medzi oboma štátmi, potvrdilo, že sa vytvoril nový spojenecký Rusko-Franc. Blok
- 1904 (8. 4.) podpísaná tzv. srdečná dohoda (entente cordiale) medzi VB a Franc. na zámku Clouds vo Franc.; zdanlivo len dohoda o rozdelení kolónií a sfér vplyvu bola vskutočnosti jedným zo základnýchkameňov sv. vojens.-politic. systému blízkej budúcnosti
- 1907 VB + Fr. + Rusko => Dohoda-záujmny eur. mocností sa stretli na Balkáne (Nemec., R-U, Ruska)
- 1908 (6. 10.) R-U si pripojilo Bosnu a Hercegovinu (anexia)
- 17. 10.1912 – 30. 5. 1913 => 1. balkánská vojna proti Turecku; koalícia balkánských štátov Bulharska,srbska, Grécka, Čiernej Hory pripravila rýchlu porážku Osmanskej ríši => mier podpísaný v Londýne, turecko ním stratilo vačšinu jeho európského územia
- 26.  6.– 10. 8. 1913 => 2. Balkánská vojna proti Bulharsku - konflikty při rozdeľovaní ziskov z 1.vojny; Bulharsko nakoniec vystúpilo proti svojim dovtedajším spojencom
  - po jeho porážke si Srbsko a Grécko rozdelili vačšinu územia Macedónie 

# Vypuknutie vojny
## 1. Nemecko hľadá zámienku na vypuknutie vojny
- Nemci hľadali zámienku na vojnu, no neodvážili sa ju rozpútať, aby nevystupovali ako agresor 

## 2.Sarajevský atentát
- jún 1914 uskutočnila rakúska armáda vojenské manévre v Bosnepod vedením vrchného inšpektora Františka Ferdinanda d’Este, následníka trónu
- 28.jún 1914 srbský študent a člen tajnej srbskej organizácie Čierná ruka a hnutia Mladá Bosna Gavrilo Princip spáchal v Sarajeve atentát na Františka Ferdinanda d’Estea jeho manželku Žofiu
- Rakúsko považovalo tento atentát za vhodnú príležitosť vystúpiť proti Srbsku, ale vojnu nechcelo
- Nemecko tlačilo na R-U, aby im vyhlásilo vojnu a pod ich vplyvom R-U vláda vypracovala ultmátum, kt. obsahovalo:
  - 1. Srbsko malo odsúdiť Veľkosrbské hnutie.
  - 2. Poďla zoznamu R-U mali byť prepustenízo srbskej armády srbskí velitelia a dostojníci.
  - 3. Srbsko malo dovoliť, aby R-U komisári na území Srbska mohli potlačiť Veľkosrbské hnutie.
- Rusko a Anglicko radilo Srbsku, aby ultimátum prijalo. Srbi sa nechceli vzdať svojej suverenityy, pretopodmienky neprijali
- 28. júl 1914 R-U vypovedalo vojnu Srbsku; začala sa 1. svetová vojna 

## 3. Rozputanie vojny
1. august 1914 vypovedalo Nemecko vojnu Rusku
2. august 1914 vypovedalo Nemecko vojnu Francúzsku
3. 3. august 1914 na protest proti obsadzovaniu belgického územia Anglicko vyhlásilo vojnu Nemecku

\begin{center}
\begin{tabular}{|c | c |}
 \hline
 Trojspolok & Dohoda \\
 \hline
 \hline
 Nemecko, RakuskoUhorsko, Turecko, Bulharsko & Francuzsko, VB, Grecko, Japonsko, Taliansko, Rumunsko, USA, Srbsko, Belgicko, Cierna Hora \\ 
 \hline
\end{tabular}
\end{center}

- ostatné európske štáty vyhláslili neutralitu
- bojovalo sa na 3 frontoch:
  - Europa: 
    - západný (Franc., ťažká zákopová vojna)
    - východný (Rusko)
    - juzny: **srbsky, solunsky, taliansky(1915)**
  - Azia:
    - Blizky vychod (VB vs Tur)
    - Daleky vychod (Jap. vs Nem)
  - Afrika:
    - bojovalo sa v 4 nemeckých kolóniách: Togo, Kmarun, Tanzánia, Namíbia
## 4. Fazy vojny
- 1. fáza: 28. júl 1914 - december 1914
- 2. fáza: 1915 - 1916
- 3. fáza: 1917 - 3. marec 1918
- 4. fáza: 3. marec 1918 - 11. november 1918

# Priebeh 1. sv. vojny
## I. Faza: 28. 7. 1914 - december 1914
### Zapadny front
- 4. august 1914 napadli Nemeci Belgicko scieľom napadnuť Francúzsko
- nemecká armáda bola zo začiatku úspešná; postupovala Franc.
  - september 1914 na rieke Marne bola nemecká armáda Francúzskom porazená
- obidve strany na rieke vykopali a opevnili zákopové systémy (dĺžka 700 a viac km; medzi nimi 100 m; tiahli sa od Lamnškého priplavu po Švajčiarsko; zákopová vojna trvala 4 roky)za celé 4 roky sa frontová línia neposunula o viac jako 65 km
### Vychodny front
- Nemecku nevyšiel plán bleskovej vojny
- na prelome r. 1914/1915 „Karpatská zima“ - ruské vojska sa dostali až na územia východného Slovenska (obsadiuli Bardejov, Medzilaborce, Svidník, Stropkov, Sninu, Humenné)
- VB 386 000 mužov, profesionálna armáda; Rusko 400 rokov pozadu a milióny mužov
  - 1914 Tannenberg (úspech)
  - 1915 pri Mazurských jazerách Nemci zabrali Rusom kontrolovateľné Poľsko
### Svetove bojiska
- 22. august 1914 Japonsko vyhlásilo vojnu Nemecku; Japonci zaútočili na nemec. kolóniu Tsing-Tan (padla za 11 týždňov)
- nemecké lode boli prenasledované až k Indickému oceánu
- posledné mesiace roku 1914 bitky o Koronel, Chille, Falklandské ostrovy 8. december 1914 nemecká východoázijská eskorta potopená, ale bojová loď Dresden unikla
## II. Faza 1915 - 1916
### Juzny front
- **1915** Taliansko vstupuje do vojny po boku Dohody, otvoril sa tal. front - úspechy R-U armáda
  - Bulharsko po boku Ústredných mocností
- 9. október 1915 nemec. + bulharské jednotky dobyli Belehrad
- do konca novembra 1915 obsadenie Srbska
- R-U na Balkáne a východnom fronte neúpešné, darilo sa mu v Tal.
  - **1916** kDohode sa pridalo Rumunsko, Nemci ho však za krátky čas obsadili
  - Január 1916 obsadili ÚM hlv. Město Čirenej Hory Cetinje
### Zapadny front
- február 1916 nemecký plán rozhodnúť vojnu na západe
- júl 1916 bitka na rieke Somme vo Francúzsku => neúspech Britov, „krvavý kúpeľ“
- december1916 útok na pevnosť Verdun (Fr.) - ostala vrukách Franc.
### Vychodny front
- víťazstvo Nemcov pri Mazúrských jazerách 1915, Nemci zabrali Rusom kontrolovateľné Poľsko
- nemec. a rakúska protiofenzíva => cieľ: dostať Rusko z vojny
  - **1916** Brussilova ofenzíva, ale aj napriek tomu ruská armáda oslabená
#### Azia
- 1915 britské námorné ťaženie pri Dardanelách
- 1915 - 1916 najvýznam. ťaženie při Gallipoli
- 1915 Briti sa chceli zmocniť Konštantinopolu
- britské, austrálske, novozélandske jednotky doslova padli k zemi pod tureckou paľbou
- pád W. Churchilla (minister námorníctva) - pre neúspech jeho vojsk v Turecku
  - od r. 1916 neustále sa zvyšuje výroba zbraní
  - branná povinnosť vo VB => minister. Predseda D. Lloyd George
- Nemec. - Hindenburg a Ludendorf (generáli)
### Vojna na Mori
- pánom mora britské namorníctvo
  - 8. máj 1915 vSevernom mori nemecká ponorka potopila britský civilný parník Lusitaniu (128 vplyvných pasažierov)
  - 1916 Jutská plytčina - jediná veľká námorná bitka 1. Sv. vojny (Briti versus Nemci) => Vb obrovské straty, ale nemecká flotila zatlačená
## III. Faza - 1917 - 3. marec 1918 
### Zapadny front
- pokračuje zákopová vojna
### Vychodny front
- revolucia v Rusku
  - 12.  marec  1917 - prevrat  v Rusku,  v Petrohrade  a  pád  cárizmu - posledný cár Mikuláš => februárová revolúcia (27.2.) => dočasná vláda: A. F. Kerenskij (1881 –1970) /advokát, minister a potom predseda dočasnej vlády/ => snaha Rusko dostať sa z krízy, nepodarilo sa, nástup boľševikov, zhodili dočasnú vládu
- 1. február 1917 Nemecko zahájilo totálnu ponorkovú vojnu
- 6. apríl 1917 USA vyhlásilo vojnu Nemecku, vstup USA do vojny
- apríl 1917 Lenin v Rusku
- zhoršujúca situácia nahrávala boľševikom
- heslo: „Okamžité ukončenie vojny“
  - 7. november 1917 (25.10.) - Veľká októbrová socialistická revolúcia (VOSR)
  - 8. november 1917 boľševický všeruský zjazd prijal:
    - A) Dekrét o miery (okamžité ukončenie vojny a zrušenie všetkých tajných cárských zmlúv s ich zverejnením)
    - B) Dekrét o pode (zrušenie veľkého sukromného vlastníctva a neurčito formulované zásady o ponechávaní pody roľníkom vychadzajúce z agrár. programu eserov)
    - C) Deklarácia práv národov Ruska na sebaurčenie - 15. 11. 1917 => Stalinom a Leninom podpísaný vládny dekrét vyhlasoval rovnoprávnosť a zvrchovanosť národov Ruska, ich právo na slobodné sebaurčenie až do odtrhnutia a vytvorenia samostat. štátu

### Juzny front
- 1917 rozhodná porážka Tal. při Caporette (Kobarit)


# Pojmy:
- **militarizmus**
  - krajina má mať silnú armádu a používať ju
- **pacifizmus**
  - vojna a násilie sú nepotrebné, konflikty by sa mali riešiť diplomaticky
  - po WWI rastie jeho popularita
- **klerikalizmus**
  - zastupovanie cirkevných názorov v politike
- **veľmoci, rovnováha veľmoci**
  - FA, VB, RUS, NEM, R-UH
  - najmocnejsie krajiny v europe
  - rovnohava = maju sa balancovat armadami a zaujmami(aby sa neopakoval Napoleon)
- **Spolok troch cisárov**
  - voľné spojenectvo Nemecka, Ruska a Rakúsko-Uhorska
  - kontrola nad východnou Európou, udržanie rovnováhy veľmocí
  - nezhody medzi členmi, 1880s - rozpad
- **Trojdohoda**
  - VB, Francúzsko, Rusko
  - na základe vzájomných dohôd medzi krajinami, menej formálna ako Trojspolok
- **Trojspolok**
  - Nemecko, Rakúsko-Uhorsko, Taliansko + Rumunsko
- **Srdečná dohoda**
  - "umierenie" Francúzska a VB, ukončenie 1000 rokov súbojov
  - hrozba agresívneho Nemecka
  - vyriešenie koloniálnych nezhod
  - základ pre Trojdohodu
- **Taliansko prevracia kabát**
  - Taliansko je súčasťou trojspolku ale vo vojne je najprv *de facto* neutrálne
    - je zle pripravené na vojnu, verejnosť chce mier, vnútorné nepokoje
  - VB sľubuje Taliansku veľké časti Rakúsko-Uhorska a jadranského pobrežia
  - marec 1915 - Taliansko vyhlasuje vonu Nemecku a Rakúsko-Uhorsku
- **všeslovanská vzájomnosť**
  - Ján Kollár
  - rozdielne jazyky sú len nárečia
  - myšlienka silného slovanského národa
- **Jar národov**
  - mnoho narodov sa pokusa o osamostatnenie a oslobodenie od monarchie
  - 1848
- **Svätá aliancia**
  - spojenie Ruska, Pruska a Rakúska po porážke Napoleona
  - katolíci (Rakúsko), protestanti (Prusko) a ortodoxní (Rusko)
  - potláčanie liberalizmu, jednota štátu a cirkvi
- **dualizmus**
  - zväzok dvoch štátov - Rakúsko-Uhorsko
  - zdieľajú vládcu a armádu, inak sú ale značne samostatné (i.e. majú vlastné parlamenty)
- **Veľkonemecká koncepcia**
  - spojenie všetkých nemecky-hovoriacich krajín
- **imperializmus, socializmu**
  - imperializmus = rozsirovanie vlady jednej krajiny na cudzich obcanov a cuzdie krajiny, casto vyuzitim vojensekj sily a ekonomickej kontroly
    - related to colonialism and empire, but it's a distinct concept
  - socializmus = politicky a ideologicky smer charakteristikcky spolocenskym vlastnictvom, typy socializmu nemaju jednu definiciu, ale spolocenske vlastnictvo je common element
  - Komunisticke manifesto 
- **reštaurácia**
  - obnovenie tradičných monarchií
- **liberalizmus**
  - sloboda, suhlas raidenych(tych na ktorymi sa vladne), rovnost pred zakonom
- **izolacionizmus**
  - typ zahranicnej politiky, kde sa vladcovia rozhodli ze neriesenie problemov inych krajin je najlepsia moznost pre ich krajinu
