---
title: Hormóny
author: Kapko
output: pdf_document
date: 8.2 - 22.2
---

# Hormóny
- endohormóny a ektohormóny
- **hormonálna sústava** sa zúčastňuje udržiavania homeostázy v organizme
- **hormóny** - biologicky aktívne látky rôzneho chemického zloženia
    - ovplyvňujú fyziologické funkcie
    - viažu sa na cieľovú bunku
    - v organizme prenášané krvou

## Hormóny bezstavovcov
- zabezpečené nevorvými bunkami
- riadia rast, regenráciu, zvliekanie kože, zmenu sfarbenia
- **Obrúčkavce a kôrovce** - len neoursekrécia
- Hmyz má tiež neurosekrečné bunky na povrchu mozgu, ale má aj sústavu žliaz v hrudi (**predhrudná žľaza**)
    - **riadi dokonalú a nedokonalú premenu** - zvliekací hormón

## Endo a ektohormóny
- **feromóny** -> vylučujú sa do prostredia na vnútrodruhovú komunikáciu, pohlavnú aktivitu a útokové reakciu
- **hlavonožce** majú vyvinuté žľazy s vnútorným vylučovaním

## Hormóny stavovcov
- **hypofýza** -> predný lalok hypofýzy, zadný lalok hypofýzy

## Predný lalok hypofýzy - Adenohypofýza
- ***hormóny predného laloka hypofýzy:***
1. somatotropný (gigantizmus, nanizmus, akromegálie)
2. glandotropné: 
    - a) tyreotropný - rast a činnosť štítne žl.
    - b) adrenokortikotropný - nadobličky
3. gonádotropné: 
    - a) proklatín
    - b) folikulostimulačný
    - c) luteinizačný

- tyreotropný - rast a činnosť štítnej žlazy
- adrenokortikotropný - ovplyvňuje tvorbu hormónov v nadobličkách
- folikulostimulačný - dozrievanie folikulov a spermií
- luteinizačný - dozrievanie vajíčok, tlmí tvorbu testosterónu
- prolaktín - ovplyvňuje tvorbu progesterónu, spúšťa laktáciu, kvalitu sexuálneho života

## Zadný lalok hypofýzy - Neurohypofýza
- hypotalamo-hypofýzny systém:
    - hormóny sa tvoria v hypotalame a do zadného laloka sa dostávajú nervovýmy vlaknami a odtiaľ do krvi
- **vazopresín** - zabezpečuje spätné vstrebávanie vody z primárneho moču
- **oxytocín** - vyvoláva sťahy hladkých svalov maternice pri pôrode a uplatňuje sa vi ischemickej fáze menštruačného cyklu, ovplyvňuje erekciu
- spúšťacie a tlmiace hormóny - uvoľňuje hormónoy adenohypofýzy

## Epifýza, šuška
- produkuje **Melatonín** - sekrécia pohlavných hormónov && spánkový režim
- sekrécia hormónu je ovplyvnená svetelným režimom


## Štítna žlaza
- dva laloky
- umiestnená po bokoch štítnej chrupky
- tvrorí sa v nej hormóny s jódom - **najdôležitejší hormón TYROXÍN:**

1. zvyšuje sa syntéza bielkovín
2. ovplyvňujú bazálny metabolizmus
3. zvyšujú využívanie kyslíka tkanivami
4. podporujú tvrobu tepla
5. pri nedostatku hormónov sa zastaví rast kostí do dĺžky, rozvojov svalov a mozgu

- nedostatok hormónov štítnej žlazy HYPOTYREÓZA
    - struma
    - v detstve -> **kretenizmus**
    - v dospelosti -> únava, depresie, obezita
- nadprodukcia hormónov HYPERTYREÓZA
- Basedowova choroba - "žabacie oči", chudosť

## Prištítne telieska
- štyri drobné telieska umiestnené na póloch štitnej žlazy na jaj zadnej ploche
- **parathormón**
    - ovplyvňuje hladinu vápnika v krvi
    - jeho nedostatok -> **tetanické kŕče**

## Detská žľaza - týmus
- **tymokrescín** - brzdí činnosť pohlavných žliaz detí
- v týmuse dozrievajú **lymfocyty T**

## Nadobličky
- párová žľaza uložená na hronom póle obličiek
- má kôru a dreň
- hormóny kôry nadobličiek
    - **mineralokortikoidy** - udržiavanie rovnováhy medzi iónmi Na a K
    - **glukokortikoidy** - hladiny glukózy, protizápalový účinok
    - **androgénne a gestagénne hormóny** - pôsobia an vývin sekundárnych pohlavných znakov

- hormóny drene nadobličiek
    - **adrenalín** - krvný tlak, činnosť srdca, zvýši hladinu glukózy
    - **noradrenalín** - zvyšovanie systolického a diastolického tlaku

## Langerhansove ostrovčeky podžalúdkovej žľaza (pankreas)
- podžalúdková žlaza 
    - exokrinná funkcia - pakreatická šťava vylučovania do tenkého čreva(do dvanástnika)
    - endorkinná funkcia - vylučovanie do krvi 
	- **inzulín**
	    - zníženie koncentrácie glukózy v krvi
	    - diabetes
	- **glukagón**
	    - zvýšenie hladiny glukózy v krvi(novotvorba glukózy z aminokyselín)

## Pohlavné žľazy
- mužské:
    - testosterón - maskulinizačný účinok
- ženské:
    - estrogén a gestagén(progesterón)
	- estrogén - vznik ženských foriem tela, ženského správania
	- bráni dozrievaniu Graafových folikulov

    - hormóny placenty
	- od konca 3. mesiaca produkuje hormón zvyšujúci produkciu estrogénu a progesterónu

## Tkanivové hormóny
- produkované špecialnymi tkanivami alebo bunkami v orgánoch
- tráviaca sústava, obličky, stena žalúdka
- medzi nervovou sústavou a hormonálnou sústavou existuje prepojenie
