---
title: "Verben mit Präpositionen"
date: "`r Sys.Date()`"
output: pdf_document
---

# Dativ
| Sloveso    | predlozka    | preklad    |
|---------------- | --------------- | --------------- |
| anrufen    | bei | volať na |
| Angst haben | vor | mať strach z |
| arbeiten    | an | pracovať na |
| aufhören   | mit | prestakť s |
| beginnen | mit | začať s |
| beitragen | zu | prispieť k |
| einladen   | zu | pozvať na |
| sich erholen | von | zotaviť sa z |
| sich erkundigen | nach | opýtať sa na (optýtať sa po)|
| erzählen | von  | povedať o |
| gratulieren | zu  | blahoželať k |
| helfen | bei  | pomôcť s |
| leiden | an  | trpieť na |
| profitieren | von  | profitovať z |
| suchen | nach  | hľadať niečo |
| telefonieren | mit  | telefonovať s |
| sich verabschieden | von  | rozlúčiť sa s |
| warnen | vor | varovať pred |
| wohnen | bei | žiť s |
| zwingen | zu | prinútiť |
| sich verstehen | mit | vychádzať s |
| träumen | von | snívať o |
| anfangen | mit | začať s |
| teilnehmen | an | zúčastniť sa |
| --- | --- | --- |
| abhangen | von | závisieť od |
| rechnen | mit | počítať s |
| gehören | zu | patriť k niečomu |
| zweifeln | an | pochybovať o niečom |
| fragen | nach | pýtať sa na niečo |

# Akusativ
| Sloveso    | predlozka    | preklad    |
|---------------- | --------------- | --------------- |
| achten | auf | dávať pozor na |
| sich aufregen | über | nadchnúť sa nad |
| sich bewerben | um | podať si prihlášku |
| bitten | um | opýtať sa na |
| danken | für | prosiť o niečo |
| denken | an | rozmýšľať o |
| diskutieren | über | diskutovať o |
| einladen | in | pozvať dnu |
| sich entscheiden | für | rozhodnúť sa pre |
| sich entschuldigen | für | ospravedlniť sa za |
| ersetzen | durch | nahradiť za |
| erzählen | über  | rozprávať sa o |
| grenzen | an | susediť s |
| sich konzentrieren | auf | sústrediť sa na |
| lachen | über | smiať sa z |
| schreiben | an | napísať na |
| sein | für / gegen | byť za / byť proti |
| streiten | um | hádať sa o |
| sich unterhalten | über | zabávať sa na |
| sich verlassen | auf | spoliehať sa na |
| verzichten | auf | zaobísť sa bez |
| sich vorbereiten | auf | pripraviť sa na |
| sich begeistern | für | nadchnúť sa pre |
| sich erinnern | an | spomenúť si |
| nachdenken | über | premýšlať nad niečím |
| sich ärgern | über | pohoršovať sa |
| sich wenden | an | zabočiť do |
| sprechen | über | rozprávať o |
| warten | auf | čakať na |
| sich freuen | auf | tešiť sa na |
| sich interesieren | für | starať sa o |
| protestieren | gegen | protestovať proti |
| sich kümern | um | starať sa o |
| --- | --- | --- |
| sich bemühen | um | snažiť sa o niečo |
