---
title: Slovenská medivojnová poézia
date: "`r Sys.Date()`"
output: pdf_document
---

# Duchovná poézia
- poézia, ktorá nemusí byť nutne náboženská, ale rieši tematiku vnútra a duše a ducha človeka
- na slovensku: tradičné, nadväzuje na hviezdoslavovskú tradíciu aj noetikou aj poetikou
- Predstavitelia: **Martin Rázus**
    - básnik, prozaik, dramatik, publicista, politik, evanjelický kňaz
    - **Mária Rázusová**
    - študoval evanjelickú teológiu v Bratislave
    - pôsobil v Modre a neskôr odišiel do Anglicka
    - po návrate kaplán a farár v Modre, Pribyline

# Katolícka moderna
- nadväzuje na duchovné tradície, ale experimentuje
- po 1948 sa odmietali prispôsobiť socialistickému režimu
- noetika: duchovné a filozofické témy: o Bohu, Zmysle života a smrti, bolesti, slobode
- berú báseň ako modlitbu, rozhovor s Bohom
- na diela mal vplyv surrealizmus, poetizmus, symbolizmus
- Predstavitelia:
    - **Rudolf Dilong, Pavel Gašparovič Hlbina, Janko Silan, Pavol Ušák-Oliva, Svetoslav Veigl...**
    - **Dilong**:
	- narodený v Trstenej a zomiera v Pittsburgu
	- 2. sv. vojna - narukoval ako vojenský farár
	- 1945 - odchádza do emigrácie
	    - Rím, Buenos Aires, Pittsburg(kláštor)
	- Mladý svadobník, Mesto s ružou, Honolulu, pieseň labute, Konvália
	- Valéria Reiszová, matka jeho dieťaťa

# Slovenský surrealizmus a nadrealizmus
- v medzivojnovom období
- od surrealizmu sa líši tým, že stále má nejakú formu intelektu a sujetu
- zborníky - **Áno a nie**, **Sen a skutočnosť**, **Vo dne a v noci**
- Silná sedma: **Rudolf Fabry, Štefan Žáry, Vladimír Reisel, Pavel Bunčák, Ján Rak, Ján Brezina, Július Lenko**
- ich vydavatelia: **Mikuláš Bakoš, Michal Považan**

# Neosymbolizmus
- Emil Boleslav Lukáč - 1900 Hodruša-Hámre - 1979 - Bratislava
    - básnik, evanjelický kňaz, prekladateľ a učiteľ
    - predstaviteľ básnického neosymbolizmu
    - prekladal z modernej francúzskej(Charles Baudelaier) a maďarskej(Endre Ady) poézie
	- neskôr prekladá aj nemeckú, orientálnu, ruskú a anglickú literatúra
    - po 1948 upadol do nemilosti a ku poézii sa vracia až v polovici 60. rokov

# Vitalizmus
- Ján Smrek(vl. m. Ján Čietek)
    - vojak v prevej svetovej vojne
    - po vojne: 6 semestrov na evanjelicko-teologickej fakulte v Bratislave
    - redaktor národných novín v Bratislave
    - založil literárno-umelecký mesačník elán v Prahe
- filozofický zdroj: filozofia elánu, vitality
- básnici sa tešia z jednoduchých vecí, chcú v živote elán a radosť, lebo to je podľa nich to čo dodáva človeku energiu žiť

# Avantgarda
- Laco Novomestský
- jedna z najvplyvnejších osobností literárnej skupiny DAV
- SNP
- rokovanie v Moskve a Londýne s E. Benešom
- po 2. sv. vojne: povereník pre školstvo a osvetu, stál na čele Matice slovenskej a Spolku slovenských básnikov
- 1951 uväznený a 1954 odsúdený v monster procese
    - nezákonne odsúdený na 10 rokov
    - 1955 prepustený a neskôr aj rehabilitovaný
