---
title: "19. storocie"
author: Kapko
output: pdf_document
---

- ***vid prezentaciu o Slovenskom Realizme***

# Prva vlna

## J. H. Vajanský
- básnické zbierky
- *Tatry a more, Spod jarma*...
- próza: Ľalia, Letiace tiene, Suchá ratolesť, Koreň a výhonky

## P. O. Hviezdoslav
- Lyrika: *Letorosty I II a III, Žalmy a hymny, Krvavé sonety, Precházdky jarom a letom, Stesky, Duzvuky*
- Epika: *Ežo a Gábor Vlkolínsky, Hájnikova žena*
- dráma: *Herodes a Herodias*
- celý život sa snažil byť **slovenským Shakespearom**
- **?asexuálne postavy?** - nepresvedčivé postavy, málo sexuality

## Elena Maróthy-Šoltesová 
- stuff + este jedna teta

## Martin Kukučin
- Keď báčik z Chocholova umrie

# Druha vlna
- socialno psychologicky realizmus
- Martin Kukučín, J. Gregor-Tajovský, Božena Slančíkova-Timrava 

### Božena Slančíkova-Timrava
- stretla sa s Hviezdoslavom a Vajanským, keď robila Hviezdoslavovej tete slúžku
- vzdelávaná doma otcom
- próza: *Skúsenosť, Hrdinovia, Skon Paľa Ročku, Ťapákovci* 

# Tretia vlna
- **medzivojnove obdobie**
