---
title: Esej Jána Johanidesa
author: Ján Kapko
output: pdf_document
---

# Esej Jána Johanidesa
"Je na nás, ako dokážeme chrániť svoje najvnútornejšie vnútro pred vplyvmi moderných démonov. Každý by mal byť opatrný, ak niekoho vpúšťa do svojho súkromia." Táto téma ma osobne zaujala najviac z ponúknutých tém, lebo si myslím, že je v dnešnej digitálnej dobe veľmi aktuálna. Preto by som sa v tejto eseji chcel zamerať na skúmanie tejto myšlienky, s ktorou osobne súhlasím, a rád by som prezentoval svoje argumenty a dôkazy, prečo s týmto tvrdením súhlasím. Moderným démonom môže byť hocičo, ale rád by som sa zameral hlavne na moderné technológie a nástrahy internetu.

Najväčším a zároveň aj naj nenápadnejším démonom internetu, je zbieranie dát používateľov sociálnych sietí a veľkých internetových spoločností ako napríklad Google alebo Amazon. "It’s a surreal experience to see all the data you’ve given a company in one place. Online and off, nearly every life choice you’ve made, every item you’ve purchased, or every website you’ve visited has been logged, categorized, and then entered in a spreadsheet to be sold off." Tento citát z článku, publikovanom v denníku New York Times, veľmi trefne približuje túto strašidelnú realitu. Každý príspevok, každý obrázok, ktorý ste kedy pridali na internet, každý nákup, ktorý ste kedy urobili cez internet, je navždy uložený v databázach danej spoločnosti. Ak sa nad tým zamyslíte, tak je to až príliš hrôzostrašné. Ako sa však tomuto môžeme vyvarovať? Jednoducho a zložito zároveň: zrušte si účty na sociálnych sieťach. Znie to síce veľmi radikálne, no je to jediný spôsob ako sa zbaviť špehovanie do vášho súkromia. Stojí vám vaše súkromie za to, že nebudete vedieť, že vaša "facebooková kamarátka" má malé šteniatko? Toto rozhodnutie je nakoniec úplne na vás.

Ďalším démonom, možno nie až tak rozšíreným, ale rovnako nebezpečným je softvér, ktorý nás špehuje. Takémuto softvéru sa hovorí "spyware" a môže ním byť ktorákoľvek aplikácia, ktorýkoľvek program, ktorý máme v mobile alebo v počítači. Ako teda môžeme vedieť, že nás nejaká aplikácia špehuje? Rovnako ako v modernom súdnictve funguje prezumpcia neviny, v počítačovom svete funguje prezumpcia spyvéru Pokiaľ nemáme prístup ku zdrojovému kódu aplikácie, ktorú používame alebo zdrojovému kódu nejakej časti aplikácie, ktorú používame, musíme predpokladať, že daná aplikácia alebo jej časť nás špehuje. Opäť, znie to veľmi radikálne a paranoidne, no toto je bohužiaľ krutá realita. Možno si teraz v duchu hovoríte: ako sa tomuto teda dá predísť? A odpoveďou je opäť ťažko a ľahko zároveň, snažením sa používať takzvaný "open-source" softvér. "Open source software is software with source code that anyone can inspect, modify, and enhance. "Source code" is the part of software that most computer users don't ever see; it's the code computer programmers can manipulate to change how a piece of software—a "program" or "application"—works. Programmers who have access to a computer program's source code can improve that program by adding features to it or fixing parts that don't always work correctly." Je to taký softvér, ktorého zdrojový kód je voľne dostupný a voľne modifikovateľný. A preto rovnako ako keď poznáme zloženie potraviny, vieme si vyvodiť jej účinky alebo škodlivé prejavy, tak isto ak poznáme zdrojový kód programu, zákonite vieme odvodiť jeho správanie a teda aj možné nebezpečie, ktoré nám z jeho strany môže hroziť. A teda ak si chceme zachovať naše súkromie, musíme používať softvér, o ktorom vieme, že nám ho neohrozuje a vieme to preto, že máme prístup ku jeho zdrojovému kódu.

Na záver by som teda ešte ráz podotkol, že ochrana pred modernými démonmi, ochrana nášho súkromia, z väčšej časti závisí len a len od nás, ľudí ktorí si ho chceme chrániť a na rozhodnutiach, ktoré pre naše súkromie urobíme. Dúfam, že som vám, milý čitateľ, umožnil pochopiť nástrahy digitálnych technológii, ktoré ja aj vy používame každý deň.
