---
title: "Tomáš Forró: Raj pre turistov, vraždenie v džungli. Thajsko tisícih rôznych úsmevmov a jednej hrôzy"
author: Ján Kapko
output: pdf_document
fontsize: 12pt
font: Calibri
indent: true
---

Reportáž novinára Tomáša Forró vydaná 16. júla 2015 sa zameriava na Thajsko, Barmu(dnešné Mjanmarsko), barmských utečencov a thajské utečenecké tábory. V reportáži autor hovorí o svojej chronologicky prvej návšteve Thajského utečeneckého tábora v roku 2012. Venuje sa politickej situácii celého regiónu, jeho histórii ale aj autorovým vlastným príhodám a rozhovorom s rozličnými ľuďmi, prevažne utečencami v táboroch. Zaujímavým použitím dialógov, výkladov a opisov nás autor vťahuje do nepredstaviteľne drsnej reality Zadnej Indie, Thajska a jeho susedov, rasizmu, korupcie a diskriminácie.

Reportáž je napísaná veľmi pútavým spôsobom. Hoci relatívne krátka, reportáž je obsahovo veľmi sýta. Nachádza sa tu mnoho informácií, faktov a obrázkov k veci. Jej čitateľnosti dopomáha autorov špecifický štýl. 
Napísaná vo forme kapitol, ktoré svojimi názvami výstižne zrkadlia svoj obsah, je reportáž rozdelená tematický a z časti aj chronologicky. Obsah kapitol je rozdelený do krátkych odsekov, ktoré na čitateľa pôsobia príjemným spôsobom a pomáhajú mu pri ich logickom pochopení autorových myšlienok a faktov. Sú často prepletané faktickými údajmi, informáciami opismi ale aj mnohými priamymi rečami a satirou.
Autor často tieto prostriedky strieda, čo má za následok, že text nepôsobí ako útržok z vysokoškolskej učebnice goegrafie a geopolitky, ale naopak, čitateľa namotáva, vyvoláva v ňom záujem pokračovať v čítaní. Subjektívne viem povedať, že ak by táto reportáž nebola napísaná týmto vskutku vábnym štýlom, tak by som ju sám pravdepodobne nebol schopný dočítať. 
Zároveň nesmieme zabudnúť autorove nepatrné, no vskutku efektné použitie satiry a vtipných poznámok, ktoré pôsobí veľmi nenútene, ako keby ani nebolo autorovým zámerom. Toto použitie satiry pomáha objektívnemu podaniu faktov, pretože autor sa nás nesnaží citovo manipulovať, ale práve naopak sa nám snaží dať čo najviac faktov na informácií aby sme si my ako čitatelia vedeli na danú tému utvoriť vlastný názor. Vnímam to ako veľké pozitívum autorovho štýlu písania.

Osobitne si myslím, že všetky reportáže Tomáša Forró sú veľmi dobre spracované aj po obsahovej aj po kompozičnej stránke. Veľmi dobre vie spracovať fakty a informácie spolu spolu s opismi a jeho vlastnými príhodami, ktoré nadobudol vďaka tomu, že v dane oblasti trávil veľa času. Tento jeho štýl vie veľmi zaujať a vtiahnuť čitateľa, ktorému nie hneď dôjde o akých skutočných hrôzach to autor hovoril. Verím, že túto reportáž by si mal prečítať každý Európan, pretože témy o utečencoch sú stále aktuálne aj dnes a hlboko sa týkajú celej Európy.
