---
title: dovody vyhry cervenych
output: pdf_document
---

# Dovody
1. CEKA, tajna bolsevicka policia - Dzerjinsky
    - fungovalo udavacstvo
2. metoda vojnoveho komunizmu
3. vojnovy komunizmus - celoplosna reqviracia 
    - vsetko co ma ekonomicku hodnotu, to si bolsevici zaberaju
    - ludia nemali co jest, co si obliect, palivo
4. vseobecna pracovna povinnost
    - kazdy musi pracovat
    - kazdy pracuje tam a robi to, co stat prikaze
5. zasobovacia diktatura
    - redistribucia materialu a surovin - nie tym co to potrebuju, ale na front
    - nezohladnovala dopyt a potreby ludi
6. bola zrusena penazna mena

# Vrchol Leninovej kariery
- **no**va **ek**onomicka **po**litika
    - NEPE 
    - nepisti 
    - obnovenie pravo na sukromne podnikanie
	- v lahsich vyrobnych sektoroch 
	- textil, topanky, kadernik, farmaceut
	- zlate 20. roky ruska
	- stabilizacia ekonomiky zapadneho ruska
- GoElRo
    - elektrifikacia ruska 
    - prichadzaju projektanti na budovanie hydroelektrickych stavieb
    - nove fromy ubytovania, nove mesta

- GozPlan 
    - statne planovanie
    - neskor vzniknu patrocnice

- vyhlasenie zvazu Sovietskych Socialistickych Republik
    - ZSSR
    - 6 oblasti
	- rusko, bielorusko, ukrajina + z.f.
	- zakaukazska federacia(griznsko, armensko, azerbajdzan)
- kominterna
    - kuminiskicka internacionala
    - export komunizmu do celeho sveta

- Dekret o cirkvi
    - likvidacia cirkvi v ruskom prostredi
    - "nabozenstvo bad, opium ludstva": Stalin
    -  odluka cirkvi od statu
	- niceni knazi, cirkevni majetok zaberany, nicenie nabozenskych vodcov
	- nariadeny ateizmus

- koncom januara 1923 Lenin zomiera
    - do vlady ide Stalin
