---
title: Dosledky 1. Sv. Vojny
author: J. Kapko
output: pdf_document
---

***washingtonska deklracia = vyzyvanie protimonarchistov aby vydrzali, nesuhlas s monarchiu
prve maje = prisiel PO Hviezdoslav do ciech; zasadnutie v martine slovenskych elit; "tisicrocne manzelstvo s madarmi to nevyslo, je cas sa rozist, skusime to s bratmi cechmi"
16.10. => pamflet "Mym narodum"; federalizacia monarchie
28.10. => 5 muzov oktobra: Rasin, Stribrny, Svehla, Kramar(rz), Vavro Srobar -> vyhlasenie cesko slovenska, koniec vojny pre rakusko uhorskay   
30.10. => stretavanie v Martine hoci nevedeli ze je vyhlasene CS; pride Hodza a Derer a oznamia im ze uz je CSR => Martinska deklaracia => slovaci sa dobrovolne prihlasia na vznik ceskoslovenska; SNR : znovuzalozenie ako najvyssi zakonodarny institut
najznamejsia klebeta => martinska deklaracia mala aj tajny dodatok: ak do desiatich rokov od vzniku ceskoslovensa, cesko pravne nezagarantuje rovnost cechov a slovakov(ak sa nestane federaciou), potom sa ma slovensko odtrhnut od prahy 
1.1.1929 => Vojtech Tuka(medium Slovak) -> uvod Vacuum Juris(stav pravnej prazdnoty) -> Tuka pojde kvoli tomu do vazenia
Zakon na ochranu demokracie => ak bol niekto prilis radikalny tak mal byt postaveny mimo zakon a jeho strana mala byt rozpustena, ak nie, tak pojde do basy
trojkralovska deklaraciu = Mafia prijma trokralovu deklaraciu: Mafia -> CSNardonyVybor neskor CSNarodneZhromazdenie***
