---
title: Folding phone - picture description
---

# Main
The picture depicts 2 smart phones. They are foldable smartphones, each of them is in a different position. The one on the left is fully folded over itself and the one on the right is not twisted or folded in any way. There appears to be Android running as an operating system, on both of these phones. They appear to be twice the width of a normal smartphone, looking more like a tablet, then an average phone. There's a small spot, clearly visible in the middle part of the top and bottom of the screen, which indicates where the phone folds.

I'd say that this a promotional picture, quite possibly taken out of an advert. Judging by the image quality, this phone is most likely a high quality product. Having no recognisable brand marks or names, this phone is probably made by a lesser known company, or just as a concept, showing how an actual product could look like. We can speculate about the fold able display. Chances are that each of the 2 halfs we get when folding the phone has a different display technology. For example, the right half could have a E-ink display which fits perfectly for people who love to read on their phone. While the left half could have a normal OLED display, acting as a everyday phone, with the picture quality you would expect from a normal phone. When unfolded or combined, they could use some new technology that would make the displays blend in create a mix of them both serving as a large screen for watching movies or playing mobile games.

Personally, I think folding smart phones are an interesting idea. While not feeling the urge to get one or use one myself, I can imagine why it would be a great fit for other people. Having a large phone that has twice the screen size as your phone nowadays, while retaining its compactness is a steal for many people. This combined with the different display technologies mentioned a moment ago, many people who like carrying a digital book reader, such as Kindle, could have basically the same reading experience but without the need to carry an additional peace of electronics.
